/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.ars.viewclient;

import java.awt.Color;
import java.io.IOException;
import java.rmi.NotBoundException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import lk.ijse.ars.dto.BookingDetailsDTO;

/**
 *
 * @author USER
 */
public class Extra extends javax.swing.JPanel {

    /**
     * Creates new form Extra
     */
    public Extra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        EX01C = new javax.swing.JLabel();
        EX01D = new javax.swing.JLabel();
        EX01A = new javax.swing.JLabel();
        EX01B = new javax.swing.JLabel();
        EX02A = new javax.swing.JLabel();
        EX02B = new javax.swing.JLabel();
        EX03A = new javax.swing.JLabel();
        EX03B = new javax.swing.JLabel();
        EX04A = new javax.swing.JLabel();
        EX04B = new javax.swing.JLabel();
        EX05A = new javax.swing.JLabel();
        EX05B = new javax.swing.JLabel();
        EX06A = new javax.swing.JLabel();
        EX06B = new javax.swing.JLabel();
        EX07A = new javax.swing.JLabel();
        EX07B = new javax.swing.JLabel();
        EX08A = new javax.swing.JLabel();
        EX08B = new javax.swing.JLabel();
        EX02C = new javax.swing.JLabel();
        EX02D = new javax.swing.JLabel();
        EX03C = new javax.swing.JLabel();
        EX03D = new javax.swing.JLabel();
        EX04C = new javax.swing.JLabel();
        EX04D = new javax.swing.JLabel();
        EX05C = new javax.swing.JLabel();
        EX05D = new javax.swing.JLabel();
        EX06C = new javax.swing.JLabel();
        EX06D = new javax.swing.JLabel();
        EX07C = new javax.swing.JLabel();
        EX07D = new javax.swing.JLabel();
        EX08C = new javax.swing.JLabel();
        EX08D = new javax.swing.JLabel();
        EX09C = new javax.swing.JLabel();
        EX09D = new javax.swing.JLabel();
        EX04E = new javax.swing.JLabel();
        EX08F = new javax.swing.JLabel();
        EX06E = new javax.swing.JLabel();
        EX03E = new javax.swing.JLabel();
        EX05E = new javax.swing.JLabel();
        EX09F = new javax.swing.JLabel();
        EX03F = new javax.swing.JLabel();
        EX07E = new javax.swing.JLabel();
        EX02E = new javax.swing.JLabel();
        EX04F = new javax.swing.JLabel();
        EX05F = new javax.swing.JLabel();
        EX09E = new javax.swing.JLabel();
        EX06F = new javax.swing.JLabel();
        EX02F = new javax.swing.JLabel();
        EX08E = new javax.swing.JLabel();
        EX07F = new javax.swing.JLabel();
        EX01F = new javax.swing.JLabel();
        EX04G = new javax.swing.JLabel();
        EX05H = new javax.swing.JLabel();
        EX08G = new javax.swing.JLabel();
        EX01G = new javax.swing.JLabel();
        EX06G = new javax.swing.JLabel();
        EX07G = new javax.swing.JLabel();
        EX08H = new javax.swing.JLabel();
        EX04H = new javax.swing.JLabel();
        EX01H = new javax.swing.JLabel();
        EX01E = new javax.swing.JLabel();
        EX02G = new javax.swing.JLabel();
        EX06H = new javax.swing.JLabel();
        EX07H = new javax.swing.JLabel();
        EX02H = new javax.swing.JLabel();
        EX05G = new javax.swing.JLabel();
        EX03G = new javax.swing.JLabel();
        EX03H = new javax.swing.JLabel();
        EX10D = new javax.swing.JLabel();
        EX10E = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        EX01C.setBackground(new java.awt.Color(153, 153, 255));
        EX01C.setOpaque(true);
        EX01C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX01CMouseClicked(evt);
            }
        });

        EX01D.setBackground(new java.awt.Color(153, 153, 255));
        EX01D.setOpaque(true);
        EX01D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX01DMouseClicked(evt);
            }
        });

        EX01A.setBackground(new java.awt.Color(153, 153, 255));
        EX01A.setOpaque(true);
        EX01A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX01AMouseClicked(evt);
            }
        });

        EX01B.setBackground(new java.awt.Color(153, 153, 255));
        EX01B.setOpaque(true);
        EX01B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX01BMouseClicked(evt);
            }
        });

        EX02A.setBackground(new java.awt.Color(153, 153, 255));
        EX02A.setOpaque(true);
        EX02A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX02AMouseClicked(evt);
            }
        });

        EX02B.setBackground(new java.awt.Color(153, 153, 255));
        EX02B.setOpaque(true);
        EX02B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX02BMouseClicked(evt);
            }
        });

        EX03A.setBackground(new java.awt.Color(153, 153, 255));
        EX03A.setOpaque(true);
        EX03A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX03AMouseClicked(evt);
            }
        });

        EX03B.setBackground(new java.awt.Color(153, 153, 255));
        EX03B.setOpaque(true);
        EX03B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX03BMouseClicked(evt);
            }
        });

        EX04A.setBackground(new java.awt.Color(153, 153, 255));
        EX04A.setOpaque(true);
        EX04A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX04AMouseClicked(evt);
            }
        });

        EX04B.setBackground(new java.awt.Color(153, 153, 255));
        EX04B.setOpaque(true);
        EX04B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX04BMouseClicked(evt);
            }
        });

        EX05A.setBackground(new java.awt.Color(153, 153, 255));
        EX05A.setOpaque(true);
        EX05A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX05AMouseClicked(evt);
            }
        });

        EX05B.setBackground(new java.awt.Color(153, 153, 255));
        EX05B.setOpaque(true);
        EX05B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX05BMouseClicked(evt);
            }
        });

        EX06A.setBackground(new java.awt.Color(153, 153, 255));
        EX06A.setOpaque(true);
        EX06A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX06AMouseClicked(evt);
            }
        });

        EX06B.setBackground(new java.awt.Color(153, 153, 255));
        EX06B.setOpaque(true);
        EX06B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX06BMouseClicked(evt);
            }
        });

        EX07A.setBackground(new java.awt.Color(153, 153, 255));
        EX07A.setOpaque(true);
        EX07A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX07AMouseClicked(evt);
            }
        });

        EX07B.setBackground(new java.awt.Color(153, 153, 255));
        EX07B.setOpaque(true);
        EX07B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX07BMouseClicked(evt);
            }
        });

        EX08A.setBackground(new java.awt.Color(153, 153, 255));
        EX08A.setOpaque(true);
        EX08A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX08AMouseClicked(evt);
            }
        });

        EX08B.setBackground(new java.awt.Color(153, 153, 255));
        EX08B.setOpaque(true);
        EX08B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX08BMouseClicked(evt);
            }
        });

        EX02C.setBackground(new java.awt.Color(153, 153, 255));
        EX02C.setOpaque(true);
        EX02C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX02CMouseClicked(evt);
            }
        });

        EX02D.setBackground(new java.awt.Color(153, 153, 255));
        EX02D.setOpaque(true);
        EX02D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX02DMouseClicked(evt);
            }
        });

        EX03C.setBackground(new java.awt.Color(153, 153, 255));
        EX03C.setOpaque(true);
        EX03C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX03CMouseClicked(evt);
            }
        });

        EX03D.setBackground(new java.awt.Color(153, 153, 255));
        EX03D.setOpaque(true);
        EX03D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX03DMouseClicked(evt);
            }
        });

        EX04C.setBackground(new java.awt.Color(153, 153, 255));
        EX04C.setOpaque(true);
        EX04C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX04CMouseClicked(evt);
            }
        });

        EX04D.setBackground(new java.awt.Color(153, 153, 255));
        EX04D.setOpaque(true);
        EX04D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX04DMouseClicked(evt);
            }
        });

        EX05C.setBackground(new java.awt.Color(153, 153, 255));
        EX05C.setOpaque(true);
        EX05C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX05CMouseClicked(evt);
            }
        });

        EX05D.setBackground(new java.awt.Color(153, 153, 255));
        EX05D.setOpaque(true);
        EX05D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX05DMouseClicked(evt);
            }
        });

        EX06C.setBackground(new java.awt.Color(153, 153, 255));
        EX06C.setOpaque(true);
        EX06C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX06CMouseClicked(evt);
            }
        });

        EX06D.setBackground(new java.awt.Color(153, 153, 255));
        EX06D.setOpaque(true);
        EX06D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX06DMouseClicked(evt);
            }
        });

        EX07C.setBackground(new java.awt.Color(153, 153, 255));
        EX07C.setOpaque(true);
        EX07C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX07CMouseClicked(evt);
            }
        });

        EX07D.setBackground(new java.awt.Color(153, 153, 255));
        EX07D.setOpaque(true);
        EX07D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX07DMouseClicked(evt);
            }
        });

        EX08C.setBackground(new java.awt.Color(153, 153, 255));
        EX08C.setOpaque(true);
        EX08C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX08CMouseClicked(evt);
            }
        });

        EX08D.setBackground(new java.awt.Color(153, 153, 255));
        EX08D.setOpaque(true);
        EX08D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX08DMouseClicked(evt);
            }
        });

        EX09C.setBackground(new java.awt.Color(153, 153, 255));
        EX09C.setOpaque(true);
        EX09C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX09CMouseClicked(evt);
            }
        });

        EX09D.setBackground(new java.awt.Color(153, 153, 255));
        EX09D.setOpaque(true);
        EX09D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX09DMouseClicked(evt);
            }
        });

        EX04E.setBackground(new java.awt.Color(153, 153, 255));
        EX04E.setOpaque(true);
        EX04E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX04EMouseClicked(evt);
            }
        });

        EX08F.setBackground(new java.awt.Color(153, 153, 255));
        EX08F.setOpaque(true);
        EX08F.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX08FMouseClicked(evt);
            }
        });

        EX06E.setBackground(new java.awt.Color(153, 153, 255));
        EX06E.setOpaque(true);
        EX06E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX06EMouseClicked(evt);
            }
        });

        EX03E.setBackground(new java.awt.Color(153, 153, 255));
        EX03E.setOpaque(true);
        EX03E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX03EMouseClicked(evt);
            }
        });

        EX05E.setBackground(new java.awt.Color(153, 153, 255));
        EX05E.setOpaque(true);
        EX05E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX05EMouseClicked(evt);
            }
        });

        EX09F.setBackground(new java.awt.Color(153, 153, 255));
        EX09F.setOpaque(true);
        EX09F.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX09FMouseClicked(evt);
            }
        });

        EX03F.setBackground(new java.awt.Color(153, 153, 255));
        EX03F.setOpaque(true);
        EX03F.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX03FMouseClicked(evt);
            }
        });

        EX07E.setBackground(new java.awt.Color(153, 153, 255));
        EX07E.setOpaque(true);
        EX07E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX07EMouseClicked(evt);
            }
        });

        EX02E.setBackground(new java.awt.Color(153, 153, 255));
        EX02E.setOpaque(true);
        EX02E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX02EMouseClicked(evt);
            }
        });

        EX04F.setBackground(new java.awt.Color(153, 153, 255));
        EX04F.setOpaque(true);
        EX04F.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX04FMouseClicked(evt);
            }
        });

        EX05F.setBackground(new java.awt.Color(153, 153, 255));
        EX05F.setOpaque(true);
        EX05F.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX05FMouseClicked(evt);
            }
        });

        EX09E.setBackground(new java.awt.Color(153, 153, 255));
        EX09E.setOpaque(true);
        EX09E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX09EMouseClicked(evt);
            }
        });

        EX06F.setBackground(new java.awt.Color(153, 153, 255));
        EX06F.setOpaque(true);
        EX06F.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX06FMouseClicked(evt);
            }
        });

        EX02F.setBackground(new java.awt.Color(153, 153, 255));
        EX02F.setOpaque(true);
        EX02F.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX02FMouseClicked(evt);
            }
        });

        EX08E.setBackground(new java.awt.Color(153, 153, 255));
        EX08E.setOpaque(true);
        EX08E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX08EMouseClicked(evt);
            }
        });

        EX07F.setBackground(new java.awt.Color(153, 153, 255));
        EX07F.setOpaque(true);
        EX07F.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX07FMouseClicked(evt);
            }
        });

        EX01F.setBackground(new java.awt.Color(153, 153, 255));
        EX01F.setOpaque(true);
        EX01F.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX01FMouseClicked(evt);
            }
        });

        EX04G.setBackground(new java.awt.Color(153, 153, 255));
        EX04G.setOpaque(true);
        EX04G.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX04GMouseClicked(evt);
            }
        });

        EX05H.setBackground(new java.awt.Color(153, 153, 255));
        EX05H.setOpaque(true);
        EX05H.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX05HMouseClicked(evt);
            }
        });

        EX08G.setBackground(new java.awt.Color(153, 153, 255));
        EX08G.setOpaque(true);
        EX08G.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX08GMouseClicked(evt);
            }
        });

        EX01G.setBackground(new java.awt.Color(153, 153, 255));
        EX01G.setOpaque(true);
        EX01G.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX01GMouseClicked(evt);
            }
        });

        EX06G.setBackground(new java.awt.Color(153, 153, 255));
        EX06G.setOpaque(true);
        EX06G.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX06GMouseClicked(evt);
            }
        });

        EX07G.setBackground(new java.awt.Color(153, 153, 255));
        EX07G.setOpaque(true);
        EX07G.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX07GMouseClicked(evt);
            }
        });

        EX08H.setBackground(new java.awt.Color(153, 153, 255));
        EX08H.setOpaque(true);
        EX08H.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX08HMouseClicked(evt);
            }
        });

        EX04H.setBackground(new java.awt.Color(153, 153, 255));
        EX04H.setOpaque(true);
        EX04H.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX04HMouseClicked(evt);
            }
        });

        EX01H.setBackground(new java.awt.Color(153, 153, 255));
        EX01H.setOpaque(true);
        EX01H.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX01HMouseClicked(evt);
            }
        });

        EX01E.setBackground(new java.awt.Color(153, 153, 255));
        EX01E.setOpaque(true);
        EX01E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX01EMouseClicked(evt);
            }
        });

        EX02G.setBackground(new java.awt.Color(153, 153, 255));
        EX02G.setOpaque(true);
        EX02G.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX02GMouseClicked(evt);
            }
        });

        EX06H.setBackground(new java.awt.Color(153, 153, 255));
        EX06H.setOpaque(true);
        EX06H.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX06HMouseClicked(evt);
            }
        });

        EX07H.setBackground(new java.awt.Color(153, 153, 255));
        EX07H.setOpaque(true);
        EX07H.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX07HMouseClicked(evt);
            }
        });

        EX02H.setBackground(new java.awt.Color(153, 153, 255));
        EX02H.setOpaque(true);
        EX02H.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX02HMouseClicked(evt);
            }
        });

        EX05G.setBackground(new java.awt.Color(153, 153, 255));
        EX05G.setOpaque(true);
        EX05G.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX05GMouseClicked(evt);
            }
        });

        EX03G.setBackground(new java.awt.Color(153, 153, 255));
        EX03G.setOpaque(true);
        EX03G.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX03GMouseClicked(evt);
            }
        });

        EX03H.setBackground(new java.awt.Color(153, 153, 255));
        EX03H.setOpaque(true);
        EX03H.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX03HMouseClicked(evt);
            }
        });

        EX10D.setBackground(new java.awt.Color(153, 153, 255));
        EX10D.setOpaque(true);
        EX10D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX10DMouseClicked(evt);
            }
        });

        EX10E.setBackground(new java.awt.Color(153, 153, 255));
        EX10E.setOpaque(true);
        EX10E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EX10EMouseClicked(evt);
            }
        });

        jLabel90.setBackground(new java.awt.Color(0, 0, 153));
        jLabel90.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(153, 153, 153));
        jLabel90.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel90.setText("1");

        jLabel91.setBackground(new java.awt.Color(0, 0, 153));
        jLabel91.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(153, 153, 153));
        jLabel91.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel91.setText("2");

        jLabel92.setBackground(new java.awt.Color(0, 0, 153));
        jLabel92.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(153, 153, 153));
        jLabel92.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel92.setText("3");

        jLabel93.setBackground(new java.awt.Color(0, 0, 153));
        jLabel93.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(153, 153, 153));
        jLabel93.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel93.setText("4");

        jLabel94.setBackground(new java.awt.Color(0, 0, 153));
        jLabel94.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(153, 153, 153));
        jLabel94.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel94.setText("5");

        jLabel95.setBackground(new java.awt.Color(0, 0, 153));
        jLabel95.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(153, 153, 153));
        jLabel95.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel95.setText("6");

        jLabel96.setBackground(new java.awt.Color(0, 0, 153));
        jLabel96.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(153, 153, 153));
        jLabel96.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel96.setText("7");

        jLabel97.setBackground(new java.awt.Color(0, 0, 153));
        jLabel97.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(153, 153, 153));
        jLabel97.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel97.setText("8");

        jLabel98.setBackground(new java.awt.Color(0, 0, 153));
        jLabel98.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel98.setForeground(new java.awt.Color(153, 153, 153));
        jLabel98.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel98.setText("9");

        jLabel99.setBackground(new java.awt.Color(0, 0, 153));
        jLabel99.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(153, 153, 153));
        jLabel99.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel99.setText("10");

        jLabel100.setBackground(new java.awt.Color(0, 0, 153));
        jLabel100.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel100.setForeground(new java.awt.Color(153, 153, 153));
        jLabel100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel100.setText("A");

        jLabel101.setBackground(new java.awt.Color(0, 0, 153));
        jLabel101.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(153, 153, 153));
        jLabel101.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel101.setText("B");

        jLabel102.setBackground(new java.awt.Color(0, 0, 153));
        jLabel102.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(153, 153, 153));
        jLabel102.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel102.setText("C");

        jLabel103.setBackground(new java.awt.Color(0, 0, 153));
        jLabel103.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(153, 153, 153));
        jLabel103.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel103.setText("D");

        jLabel104.setBackground(new java.awt.Color(0, 0, 153));
        jLabel104.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(153, 153, 153));
        jLabel104.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel104.setText("E");

        jLabel105.setBackground(new java.awt.Color(0, 0, 153));
        jLabel105.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(153, 153, 153));
        jLabel105.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel105.setText("F");

        jLabel106.setBackground(new java.awt.Color(0, 0, 153));
        jLabel106.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel106.setForeground(new java.awt.Color(153, 153, 153));
        jLabel106.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel106.setText("G");

        jLabel107.setBackground(new java.awt.Color(0, 0, 153));
        jLabel107.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(153, 153, 153));
        jLabel107.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel107.setText("H");

        jLabel108.setBackground(new java.awt.Color(0, 0, 153));
        jLabel108.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel108.setForeground(new java.awt.Color(153, 153, 153));
        jLabel108.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel108.setText("11");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(153, 153, 153));
        lblTitle.setText("EXTRA CLASS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel92, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel94, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel95, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel96, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel97, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel98, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel99, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel91, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel108, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(EX01A, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EX01B, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(EX02A, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EX02B, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(EX03A, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EX03B, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(EX04A, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EX04B, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(EX05A, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EX05B, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(EX06A, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EX06B, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(EX07A, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EX07B, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(EX08A, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EX08B, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(EX02C, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(EX02D, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(EX03C, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(EX03D, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(EX04C, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(EX04D, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(EX05C, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(EX05D, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(EX06C, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(EX06D, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(EX07C, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(EX07D, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(EX08C, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(EX08D, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(EX09C, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(EX09D, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(EX02E, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(EX02F, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(EX03E, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(EX03F, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(EX04E, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(EX04F, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(EX05E, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(EX05F, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(EX06E, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(EX06F, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(EX07E, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(EX07F, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(EX08E, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(EX08F, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(EX09E, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(EX09F, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(EX10D, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EX10E, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(EX01C, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EX01D, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EX01E, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EX01F, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(EX01G, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EX01H, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(EX02G, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EX02H, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(EX03G, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EX03H, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(EX04G, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EX04H, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(EX05G, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EX05H, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(EX06G, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EX06H, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(EX07G, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EX07H, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(EX08G, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EX08H, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel100, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel101, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel102, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel103, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel104, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel105, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel106, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel107, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel101, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel100, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel103, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel102, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel105, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel104, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel107, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel106, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel91, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel92, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel94, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel95, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel96, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel97, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel98, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel99, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EX01H, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EX01G, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EX02H, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EX02G, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EX03H, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EX03G, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EX04H, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EX04G, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EX05H, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EX05G, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EX06H, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EX06G, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EX07H, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EX07G, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EX08H, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EX08G, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EX01D, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EX01C, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EX01F, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EX01E, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EX02D, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EX02C, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EX03D, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EX03C, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EX04D, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EX04C, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EX05D, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EX05C, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EX06D, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EX06C, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EX07D, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EX07C, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EX08D, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EX08C, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EX09D, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EX09C, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EX02F, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EX02E, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EX03F, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EX03E, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EX04F, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EX04E, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EX05F, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EX05E, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EX06F, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EX06E, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EX07F, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EX07E, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EX08F, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EX08E, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EX09F, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EX09E, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EX10D, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EX10E, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EX01B, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EX01A, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EX02B, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EX02A, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EX03B, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EX03A, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EX04B, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EX04A, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EX05B, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EX05A, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EX06B, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EX06A, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EX07B, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EX07A, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EX08B, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EX08A, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel108, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EX01AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX01AMouseClicked
        addTem("EX01A",EX01A.getBackground());
    }//GEN-LAST:event_EX01AMouseClicked

    private void EX01BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX01BMouseClicked
        addTem("EX01B", EX01B.getBackground());
    }//GEN-LAST:event_EX01BMouseClicked

    private void EX01CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX01CMouseClicked
        addTem("EX01C", EX01C.getBackground());
    }//GEN-LAST:event_EX01CMouseClicked

    private void EX01DMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX01DMouseClicked
        addTem("EX01D", EX01D.getBackground());
    }//GEN-LAST:event_EX01DMouseClicked

    private void EX01EMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX01EMouseClicked
        addTem("EX01E", EX01E.getBackground());
    }//GEN-LAST:event_EX01EMouseClicked

    private void EX01FMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX01FMouseClicked
        addTem("EX01F", EX01F.getBackground());
    }//GEN-LAST:event_EX01FMouseClicked

    private void EX01GMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX01GMouseClicked
        addTem("EX01G", EX01G.getBackground());
    }//GEN-LAST:event_EX01GMouseClicked

    private void EX01HMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX01HMouseClicked
        addTem("EX01H", EX01H.getBackground());
    }//GEN-LAST:event_EX01HMouseClicked

    private void EX02AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX02AMouseClicked
       addTem("EX02A", EX02A.getBackground());
    }//GEN-LAST:event_EX02AMouseClicked

    private void EX02BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX02BMouseClicked
        addTem("EX02B", EX02B.getBackground());
    }//GEN-LAST:event_EX02BMouseClicked

    private void EX02CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX02CMouseClicked
        addTem("EX02C", EX02C.getBackground());
    }//GEN-LAST:event_EX02CMouseClicked

    private void EX02DMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX02DMouseClicked
        addTem("EX02D", EX02D.getBackground());
    }//GEN-LAST:event_EX02DMouseClicked

    private void EX02EMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX02EMouseClicked
        addTem("EX02E", EX02E.getBackground());
    }//GEN-LAST:event_EX02EMouseClicked

    private void EX02FMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX02FMouseClicked
        addTem("EX02F", EX02F.getBackground());
    }//GEN-LAST:event_EX02FMouseClicked

    private void EX02GMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX02GMouseClicked
        addTem("EX02G", EX02G.getBackground());
    }//GEN-LAST:event_EX02GMouseClicked

    private void EX02HMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX02HMouseClicked
        addTem("EX02H", EX02H.getBackground());
    }//GEN-LAST:event_EX02HMouseClicked

    private void EX03AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX03AMouseClicked
        addTem("EX03A", EX03A.getBackground());
    }//GEN-LAST:event_EX03AMouseClicked

    private void EX03BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX03BMouseClicked
        addTem("EX03B", EX03B.getBackground());
    }//GEN-LAST:event_EX03BMouseClicked

    private void EX03CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX03CMouseClicked
        addTem("EX03C", EX03C.getBackground());
    }//GEN-LAST:event_EX03CMouseClicked

    private void EX03DMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX03DMouseClicked
        addTem("EX03D", EX03D.getBackground());
    }//GEN-LAST:event_EX03DMouseClicked

    private void EX03EMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX03EMouseClicked
        addTem("EX03E", EX03E.getBackground());
    }//GEN-LAST:event_EX03EMouseClicked

    private void EX03FMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX03FMouseClicked
        addTem("EX03F", EX03F.getBackground());
    }//GEN-LAST:event_EX03FMouseClicked

    private void EX03GMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX03GMouseClicked
        addTem("EX03G", EX03G.getBackground());
    }//GEN-LAST:event_EX03GMouseClicked

    private void EX03HMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX03HMouseClicked
        addTem("EX03H", EX03H.getBackground());
    }//GEN-LAST:event_EX03HMouseClicked

    private void EX04AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX04AMouseClicked
        addTem("EX04A", EX04A.getBackground());
    }//GEN-LAST:event_EX04AMouseClicked

    private void EX04BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX04BMouseClicked
        addTem("EX04B", EX04B.getBackground());
    }//GEN-LAST:event_EX04BMouseClicked

    private void EX04CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX04CMouseClicked
        addTem("EX04C", EX04C.getBackground());
    }//GEN-LAST:event_EX04CMouseClicked

    private void EX04DMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX04DMouseClicked
        addTem("EX04D", EX04D.getBackground());
    }//GEN-LAST:event_EX04DMouseClicked

    private void EX04EMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX04EMouseClicked
        addTem("EX04E", EX04E.getBackground());
    }//GEN-LAST:event_EX04EMouseClicked

    private void EX04FMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX04FMouseClicked
        addTem("EX04F", EX04F.getBackground());
    }//GEN-LAST:event_EX04FMouseClicked

    private void EX04GMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX04GMouseClicked
        addTem("EX04G", EX04G.getBackground());
    }//GEN-LAST:event_EX04GMouseClicked

    private void EX04HMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX04HMouseClicked
        addTem("EX04H", EX04H.getBackground());
    }//GEN-LAST:event_EX04HMouseClicked

    private void EX05AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX05AMouseClicked
        addTem("EX05A", EX05A.getBackground());
    }//GEN-LAST:event_EX05AMouseClicked

    private void EX05BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX05BMouseClicked
        addTem("EX05B", EX05B.getBackground());
    }//GEN-LAST:event_EX05BMouseClicked

    private void EX05CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX05CMouseClicked
        addTem("EX05C", EX05C.getBackground());
    }//GEN-LAST:event_EX05CMouseClicked

    private void EX05DMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX05DMouseClicked
        addTem("EX05D", EX05D.getBackground());
    }//GEN-LAST:event_EX05DMouseClicked

    private void EX05EMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX05EMouseClicked
        addTem("EX05E", EX05E.getBackground());
    }//GEN-LAST:event_EX05EMouseClicked

    private void EX05FMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX05FMouseClicked
        addTem("EX05F", EX05F.getBackground());
    }//GEN-LAST:event_EX05FMouseClicked

    private void EX05GMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX05GMouseClicked
        addTem("EX05G", EX05G.getBackground());
    }//GEN-LAST:event_EX05GMouseClicked

    private void EX05HMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX05HMouseClicked
        addTem("EX05H", EX05H.getBackground());
    }//GEN-LAST:event_EX05HMouseClicked

    private void EX06AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX06AMouseClicked
        addTem("EX06A", EX06A.getBackground());
    }//GEN-LAST:event_EX06AMouseClicked

    private void EX06BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX06BMouseClicked
        addTem("EX06B", EX06B.getBackground());
    }//GEN-LAST:event_EX06BMouseClicked

    private void EX06CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX06CMouseClicked
        addTem("EX06C", EX06C.getBackground());
    }//GEN-LAST:event_EX06CMouseClicked

    private void EX06DMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX06DMouseClicked
        addTem("EX06D", EX06D.getBackground());
    }//GEN-LAST:event_EX06DMouseClicked

    private void EX06EMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX06EMouseClicked
        addTem("EX06E", EX06E.getBackground());
    }//GEN-LAST:event_EX06EMouseClicked

    private void EX06FMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX06FMouseClicked
        addTem("EX06F", EX06F.getBackground());
    }//GEN-LAST:event_EX06FMouseClicked

    private void EX06GMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX06GMouseClicked
        addTem("EX06G", EX06G.getBackground());
    }//GEN-LAST:event_EX06GMouseClicked

    private void EX06HMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX06HMouseClicked
        addTem("EX06H", EX06H.getBackground());
    }//GEN-LAST:event_EX06HMouseClicked

    private void EX07AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX07AMouseClicked
        addTem("EX07A", EX07A.getBackground());
    }//GEN-LAST:event_EX07AMouseClicked

    private void EX07BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX07BMouseClicked
        addTem("EX07B", EX07B.getBackground());
    }//GEN-LAST:event_EX07BMouseClicked

    private void EX07CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX07CMouseClicked
        addTem("EX07C", EX07C.getBackground());
    }//GEN-LAST:event_EX07CMouseClicked

    private void EX07DMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX07DMouseClicked
        addTem("EX07D", EX07D.getBackground());
    }//GEN-LAST:event_EX07DMouseClicked

    private void EX07EMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX07EMouseClicked
        addTem("EX07E", EX07E.getBackground());
    }//GEN-LAST:event_EX07EMouseClicked

    private void EX07FMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX07FMouseClicked
        addTem("EX07F", EX07F.getBackground());
    }//GEN-LAST:event_EX07FMouseClicked

    private void EX07GMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX07GMouseClicked
        addTem("EX07G", EX07G.getBackground());
    }//GEN-LAST:event_EX07GMouseClicked

    private void EX07HMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX07HMouseClicked
        addTem("EX07H", EX07H.getBackground());
    }//GEN-LAST:event_EX07HMouseClicked

    private void EX08AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX08AMouseClicked
        addTem("EX08A", EX08A.getBackground());
    }//GEN-LAST:event_EX08AMouseClicked

    private void EX08BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX08BMouseClicked
        addTem("EX08B", EX08B.getBackground());
    }//GEN-LAST:event_EX08BMouseClicked

    private void EX08CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX08CMouseClicked
        addTem("EX08C", EX08C.getBackground());
    }//GEN-LAST:event_EX08CMouseClicked

    private void EX08DMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX08DMouseClicked
        addTem("EX08D", EX08D.getBackground());
    }//GEN-LAST:event_EX08DMouseClicked

    private void EX08EMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX08EMouseClicked
        addTem("EX08E", EX08E.getBackground());
    }//GEN-LAST:event_EX08EMouseClicked

    private void EX08FMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX08FMouseClicked
        addTem("EX08F", EX08F.getBackground());
    }//GEN-LAST:event_EX08FMouseClicked

    private void EX08GMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX08GMouseClicked
        addTem("EX08G", EX08G.getBackground());
    }//GEN-LAST:event_EX08GMouseClicked

    private void EX08HMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX08HMouseClicked
        addTem("EX08H", EX08H.getBackground());
    }//GEN-LAST:event_EX08HMouseClicked

    private void EX09CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX09CMouseClicked
        addTem("EX09C", EX09C.getBackground());
    }//GEN-LAST:event_EX09CMouseClicked

    private void EX09DMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX09DMouseClicked
        addTem("EX09D", EX09D.getBackground());
    }//GEN-LAST:event_EX09DMouseClicked

    private void EX09EMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX09EMouseClicked
        addTem("EX09E", EX09E.getBackground());
    }//GEN-LAST:event_EX09EMouseClicked

    private void EX09FMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX09FMouseClicked
        addTem("EX09F", EX09F.getBackground());
    }//GEN-LAST:event_EX09FMouseClicked

    private void EX10DMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX10DMouseClicked
        addTem("EX10D", EX10D.getBackground());
    }//GEN-LAST:event_EX10DMouseClicked

    private void EX10EMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EX10EMouseClicked
        addTem("EX10E", EX10E.getBackground());
    }//GEN-LAST:event_EX10EMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EX01A;
    private javax.swing.JLabel EX01B;
    private javax.swing.JLabel EX01C;
    private javax.swing.JLabel EX01D;
    private javax.swing.JLabel EX01E;
    private javax.swing.JLabel EX01F;
    private javax.swing.JLabel EX01G;
    private javax.swing.JLabel EX01H;
    private javax.swing.JLabel EX02A;
    private javax.swing.JLabel EX02B;
    private javax.swing.JLabel EX02C;
    private javax.swing.JLabel EX02D;
    private javax.swing.JLabel EX02E;
    private javax.swing.JLabel EX02F;
    private javax.swing.JLabel EX02G;
    private javax.swing.JLabel EX02H;
    private javax.swing.JLabel EX03A;
    private javax.swing.JLabel EX03B;
    private javax.swing.JLabel EX03C;
    private javax.swing.JLabel EX03D;
    private javax.swing.JLabel EX03E;
    private javax.swing.JLabel EX03F;
    private javax.swing.JLabel EX03G;
    private javax.swing.JLabel EX03H;
    private javax.swing.JLabel EX04A;
    private javax.swing.JLabel EX04B;
    private javax.swing.JLabel EX04C;
    private javax.swing.JLabel EX04D;
    private javax.swing.JLabel EX04E;
    private javax.swing.JLabel EX04F;
    private javax.swing.JLabel EX04G;
    private javax.swing.JLabel EX04H;
    private javax.swing.JLabel EX05A;
    private javax.swing.JLabel EX05B;
    private javax.swing.JLabel EX05C;
    private javax.swing.JLabel EX05D;
    private javax.swing.JLabel EX05E;
    private javax.swing.JLabel EX05F;
    private javax.swing.JLabel EX05G;
    private javax.swing.JLabel EX05H;
    private javax.swing.JLabel EX06A;
    private javax.swing.JLabel EX06B;
    private javax.swing.JLabel EX06C;
    private javax.swing.JLabel EX06D;
    private javax.swing.JLabel EX06E;
    private javax.swing.JLabel EX06F;
    private javax.swing.JLabel EX06G;
    private javax.swing.JLabel EX06H;
    private javax.swing.JLabel EX07A;
    private javax.swing.JLabel EX07B;
    private javax.swing.JLabel EX07C;
    private javax.swing.JLabel EX07D;
    private javax.swing.JLabel EX07E;
    private javax.swing.JLabel EX07F;
    private javax.swing.JLabel EX07G;
    private javax.swing.JLabel EX07H;
    private javax.swing.JLabel EX08A;
    private javax.swing.JLabel EX08B;
    private javax.swing.JLabel EX08C;
    private javax.swing.JLabel EX08D;
    private javax.swing.JLabel EX08E;
    private javax.swing.JLabel EX08F;
    private javax.swing.JLabel EX08G;
    private javax.swing.JLabel EX08H;
    private javax.swing.JLabel EX09C;
    private javax.swing.JLabel EX09D;
    private javax.swing.JLabel EX09E;
    private javax.swing.JLabel EX09F;
    private javax.swing.JLabel EX10D;
    private javax.swing.JLabel EX10E;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    private void addTem(String eX01A, Color background) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//        Date date = dateText.getDate();
//        String showDate = sdf.format(date);
//        String showTime = (String) showTimeCombo.getSelectedItem();
//        String seatType = (String) typeCombo.getSelectedItem();
//        Date date = 
        
//        String resSeatNo;
//        BookingDetailsDTO bookingDetailsDTO;
//
//        if (color == Color.CYAN) {
//            try {
//                resSeatNo = seatNo;
//                bookingDetailsDTO = new BookingDetailsDTO(showDate, showTime, seatType, seatNo);
//                TemReservationController trc = ServerConnector.getServerConnector().geTemReservationController();
//
//                boolean added = trc.add(temReservationDTO);
//                if (added) {
//                    SelectColorChange(seatLabel, color);
//                    seatCountText.setText(Integer.toString(++seatCount));
//                    fullText.requestFocusInWindow();
//                    seatNoList.add(seatNo);
//                    labelList.add(seatLabel);
//                    fullPriceText.requestFocusInWindow();
//                }
//            } catch (IOException ex) {
//                Logger.getLogger(HomeForm.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (ParseException ex) {
//                Logger.getLogger(HomeForm.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (NotBoundException ex) {
//                Logger.getLogger(HomeForm.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        } else if (color == Color.BLUE) {
//            try {
//                temReservationDTO = new TemReservationDTO(showDate, showTime, seatType, seatNo);
//                TemReservationController trc = ServerConnector.getServerConnector().geTemReservationController();
//                boolean deleted = trc.delete(temReservationDTO);
//                if (deleted) {
//                    SelectColorChange(seatLabel, color);
//                    seatCountText.setText(Integer.toString(--seatCount));
//                    fullText.setText("");
//                    haifText.setText("");
//                    balanceText.setText("");
//                    fullText.requestFocusInWindow();
//                    seatNoList.remove(seatNo);
//                    labelList.remove(seatLabel);
//                }
//            } catch (IOException ex) {
//                Logger.getLogger(HomeForm.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (NotBoundException ex) {
//                Logger.getLogger(HomeForm.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
//        if (typeCombo.getSelectedItem().equals("Balcony Box") || typeCombo.getSelectedItem().equals("ODC Box")) {
//            fullText.setEditable(false);
//            fullText.setText(seatCountText.getText());
//            haifText.setText("00");
//        }
//    }
//
//    private void SelectColorChange(JLabel seatLabel, Color color) {
//        if (color == Color.CYAN) {
//            seatLabel.setBackground(Color.blue);
//        }
//        if (color == Color.BLUE) {
//            seatLabel.setBackground(Color.cyan);
        }
    }

