/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.ars.viewclient;

import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import javax.swing.Timer;

/**
 *
 * @author USER
 */
public class Home extends javax.swing.JPanel {
    private final Timer timer;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setDate();
        setTime();
         lblImage1.setLocation(-lblImage1.getWidth(), 0);
         lblImage2.setLocation(-lblImage2.getWidth(), 300);
         lblImage3.setLocation(-lblImage2.getWidth(), 300);
        timer = new Timer(500,new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent e) {
                int x = lblImage1.getLocation().x;
                int y = lblImage1.getLocation().y;
                
                int x2 = lblImage2.getLocation().x;
                int y2 = lblImage2.getLocation().y;
                
                int x3 = lblImage3.getLocation().x;
                int y3 = lblImage3.getLocation().y;
                
                x += 25;
                lblImage1.setLocation(x,y);
                lblImage2.setLocation(x,y);
                lblImage3.setLocation(x,y);
                
                if (x > Home.this.getWidth()){
                    lblImage1.setLocation(-lblImage1.getWidth(),0);
                    lblImage2.setLocation(-lblImage2.getWidth(),300);
                    lblImage3.setLocation(-lblImage3.getWidth(),300);
                }
            }
        });
        
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblDateMain = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTimeMain = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblImage1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblImage2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblImage3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("AIRGO ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, -1, 60));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Recevation System");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 720, -1, -1));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 1170, 70));

        lblDateMain.setBackground(new java.awt.Color(153, 204, 255));
        lblDateMain.setFont(new java.awt.Font("Algerian", 0, 33)); // NOI18N
        lblDateMain.setForeground(new java.awt.Color(255, 255, 255));
        lblDateMain.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lblDateMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 260, 50));

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTimeMain.setBackground(new java.awt.Color(153, 204, 255));
        lblTimeMain.setFont(new java.awt.Font("Algerian", 0, 33)); // NOI18N
        lblTimeMain.setForeground(new java.awt.Color(255, 255, 255));
        lblTimeMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(lblTimeMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 60, 280, 70));

        jLabel8.setFont(new java.awt.Font("Castellar", 2, 33)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Reservation System");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 420, 40));

        jLabel10.setFont(new java.awt.Font("Algerian", 0, 84)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 255));
        jLabel10.setText("AirGO");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 410, 90));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ars/icon/Iconic_2718(0)_96.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 80, 60));

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setOpaque(true);
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 140));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 140));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ars/image/2315714_300.jpg"))); // NOI18N
        jPanel6.add(lblImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 224));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ars/image/overcoming-fear-of-flying.jpg"))); // NOI18N
        jPanel5.add(lblImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 240));

        lblImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ars/image/21716735_l-1024x671.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 90, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(lblImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 340, 220));

        jPanel6.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 18, 810, 240));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 1130, 260));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1170, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblDateMain;
    private javax.swing.JLabel lblImage1;
    private javax.swing.JLabel lblImage2;
    private javax.swing.JLabel lblImage3;
    private javax.swing.JLabel lblTimeMain;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        java.util.Date d1 = new java.util.Date();
        SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-dd");
        String formateDate = df.format(d1);
        lblDateMain.setText(formateDate);
    }

    private void setTime() {
        java.util.Date d1 = new java.util.Date();
        SimpleDateFormat df = new SimpleDateFormat("HH:mm:ss");
        String formateDate = df.format(d1);
        lblTimeMain.setText(formateDate);
    }
}
 

