/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.ars.viewclient;

import com.sun.org.apache.xml.internal.dtm.DTM;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.ars.controller.ManageAirportController;
import lk.ijse.ars.controller.ManageFlightController;
import lk.ijse.ars.controller.ManageShceduleController;
import lk.ijse.ars.dto.AirportDTO;
import lk.ijse.ars.dto.FlightDTO;
import lk.ijse.ars.dto.ShceduleDTO;
import lk.ijse.ars.viewserver.AddNewAirline;

/**
 *
 * @author USER
 */
public class NewBooking extends javax.swing.JPanel {
    private ManageAirportController manageAirportController;
    /**
     * Creates new form NewBooking
     */
    public NewBooking() {
        initComponents();
        setDate();
        setTime();
        loadcmbOrigin();
        loadcmbDestination();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnlpasengerLoad = new javax.swing.JPanel();
        jLabel165 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel169 = new javax.swing.JLabel();
        jLabel171 = new javax.swing.JLabel();
        jLabel170 = new javax.swing.JLabel();
        jLabel168 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel188 = new javax.swing.JLabel();
        jLabel189 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoadFlight = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        cmbOrigin = new javax.swing.JComboBox();
        comboTripTYpe = new javax.swing.JComboBox();
        cmbDestination = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        departureDateChooser = new com.toedter.calendar.JDateChooser();
        returnDateChooser = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jSpinField3 = new com.toedter.components.JSpinField();
        jSpinField2 = new com.toedter.components.JSpinField();
        jSpinField1 = new com.toedter.components.JSpinField();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlDetails = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        pnlClassLoad = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lblBusinessClass = new javax.swing.JLabel();
        lblExtra = new javax.swing.JLabel();
        lblEconomic = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ars/icon/octicons_f076(0)_48.png"))); // NOI18N
        jLabel3.setText("Booking");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 110, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ars/icon/Duspin_Red_(32).png"))); // NOI18N
        jLabel2.setText("Delete");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, 90, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ars/icon/Material Icons_e22b(0)_32.png"))); // NOI18N
        jLabel1.setText("Update");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 90, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 1170, 60));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Castellar", 0, 26)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Reservation System");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 400, 40));

        jLabel15.setFont(new java.awt.Font("Algerian", 0, 56)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 255));
        jLabel15.setText("AirGO");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ars/icon/Iconic_2718(0)_96.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 80, 60));

        jLabel4.setBackground(new java.awt.Color(0, 0, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setOpaque(true);
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 80));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 80));

        jPanel13.setBackground(new java.awt.Color(153, 153, 153));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setOpaque(true);
        jPanel13.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 90, 20));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setOpaque(true);
        jPanel13.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 90, 20));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setOpaque(true);
        jPanel13.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 90, 20));

        jLabel33.setBackground(new java.awt.Color(204, 204, 204));
        jLabel33.setText("Business Class");
        jLabel33.setToolTipText("4500/=");
        jLabel33.setOpaque(true);
        jPanel13.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 170, 25));

        jLabel34.setBackground(new java.awt.Color(204, 204, 204));
        jLabel34.setText("Economy Class");
        jLabel34.setToolTipText("1500/=");
        jLabel34.setOpaque(true);
        jPanel13.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 170, 25));

        jLabel35.setBackground(new java.awt.Color(204, 204, 204));
        jLabel35.setText("Extra Class");
        jLabel35.setToolTipText("3500/=");
        jLabel35.setOpaque(true);
        jPanel13.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, 25));

        jLabel36.setBackground(new java.awt.Color(51, 51, 51));
        jLabel36.setOpaque(true);
        jPanel13.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 30, 30));

        jLabel32.setBackground(new java.awt.Color(204, 0, 51));
        jLabel32.setOpaque(true);
        jPanel13.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 30, 30));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Seat Map");
        jLabel6.setOpaque(true);
        jPanel13.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 140, 30));

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Booking Seats");
        jLabel12.setOpaque(true);
        jPanel13.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 140, 30));

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Receve Seats");
        jLabel13.setOpaque(true);
        jPanel13.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 140, 30));

        pnlpasengerLoad.setBackground(new java.awt.Color(153, 153, 153));

        jLabel165.setBackground(new java.awt.Color(0, 0, 0));
        jLabel165.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel165.setForeground(new java.awt.Color(204, 204, 204));
        jLabel165.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel165.setText("A");
        jLabel165.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel165.setOpaque(true);

        jLabel101.setBackground(new java.awt.Color(0, 0, 0));
        jLabel101.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(204, 204, 204));
        jLabel101.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel101.setText("F");
        jLabel101.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel101.setOpaque(true);

        jLabel5.setText("Window Seat");

        jLabel169.setBackground(new java.awt.Color(0, 0, 0));
        jLabel169.setText("1f");
        jLabel169.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel169.setOpaque(true);

        jLabel171.setBackground(new java.awt.Color(0, 0, 0));
        jLabel171.setText("1f");
        jLabel171.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel171.setOpaque(true);

        jLabel170.setBackground(new java.awt.Color(0, 0, 0));
        jLabel170.setText("1f");
        jLabel170.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel170.setOpaque(true);

        jLabel168.setBackground(new java.awt.Color(0, 0, 0));
        jLabel168.setText("1f");
        jLabel168.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel168.setOpaque(true);

        jLabel10.setText("Window Seat");

        jLabel7.setText("Window Seat");

        jLabel188.setBackground(new java.awt.Color(0, 0, 0));
        jLabel188.setText("1f");
        jLabel188.setOpaque(true);

        jLabel189.setBackground(new java.awt.Color(0, 0, 0));
        jLabel189.setText("1f");
        jLabel189.setOpaque(true);

        javax.swing.GroupLayout pnlpasengerLoadLayout = new javax.swing.GroupLayout(pnlpasengerLoad);
        pnlpasengerLoad.setLayout(pnlpasengerLoadLayout);
        pnlpasengerLoadLayout.setHorizontalGroup(
            pnlpasengerLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlpasengerLoadLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(pnlpasengerLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlpasengerLoadLayout.createSequentialGroup()
                        .addComponent(jLabel165, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel101, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlpasengerLoadLayout.createSequentialGroup()
                        .addComponent(jLabel169, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel171, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlpasengerLoadLayout.createSequentialGroup()
                        .addComponent(jLabel168, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel170, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlpasengerLoadLayout.createSequentialGroup()
                        .addComponent(jLabel188, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel189, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        pnlpasengerLoadLayout.setVerticalGroup(
            pnlpasengerLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpasengerLoadLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(pnlpasengerLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel165, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel101, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(pnlpasengerLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel169, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel171, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlpasengerLoadLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel10)))
                .addGap(6, 6, 6)
                .addGroup(pnlpasengerLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel168, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel170, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pnlpasengerLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel188, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel189, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jPanel13.add(pnlpasengerLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 160, 220, 460));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 80, 220, 630));

        jPanel9.setBackground(new java.awt.Color(255, 255, 153));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 11, 128, 26));

        jLabel17.setText("ID :");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 75, 31, 22));
        jPanel4.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 71, 128, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("YYYY / MM / DD");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 47, 128, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("HH : MM : SS");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 47, 127, -1));

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 11, 96, 30));

        tblLoadFlight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight No", "Name", "Type", "Origin Time", "Destination Time"
            }
        ));
        tblLoadFlight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoadFlightMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLoadFlight);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 428, 430, 120));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel7.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 10, 60));

        cmbOrigin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Leving From -" }));
        jPanel7.add(cmbOrigin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 420, 40));

        comboTripTYpe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UP & Down", "One Way" }));
        comboTripTYpe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTripTYpeActionPerformed(evt);
            }
        });
        jPanel7.add(comboTripTYpe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 420, 40));

        cmbDestination.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Going To -" }));
        jPanel7.add(cmbDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 420, 40));

        jLabel29.setText("Departure Date");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 187, 22));

        jLabel19.setText("Return Date :");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 187, 22));
        jPanel7.add(departureDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 187, 36));
        jPanel7.add(returnDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 187, 36));
        jPanel7.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 420, 10));

        jLabel24.setText("Baby :");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 50, 20));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Aldues :");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 60, 20));

        jLabel30.setText("Children :");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 60, 20));
        jPanel7.add(jSpinField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 60, 40));
        jPanel7.add(jSpinField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 60, 40));
        jPanel7.add(jSpinField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 60, 40));

        jLabel14.setOpaque(true);
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 420, 40));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, 30));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 500, 520));

        javax.swing.GroupLayout pnlDetailsLayout = new javax.swing.GroupLayout(pnlDetails);
        pnlDetails.setLayout(pnlDetailsLayout);
        pnlDetailsLayout.setHorizontalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        pnlDetailsLayout.setVerticalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel4.add(pnlDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 420, -1));

        jPanel9.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 540, 560));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 560, 580));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 350, 440));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout pnlClassLoadLayout = new javax.swing.GroupLayout(pnlClassLoad);
        pnlClassLoad.setLayout(pnlClassLoadLayout);
        pnlClassLoadLayout.setHorizontalGroup(
            pnlClassLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        pnlClassLoadLayout.setVerticalGroup(
            pnlClassLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jPanel11.add(pnlClassLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 350, 430));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Business Class"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Econimic Class"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Extra Class"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("00");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("00");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("00");

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("OK");
        jLabel11.setOpaque(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel11.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 350, 110));

        jPanel12.setBackground(new java.awt.Color(51, 51, 51));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBusinessClass.setBackground(new java.awt.Color(51, 51, 51));
        lblBusinessClass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblBusinessClass.setForeground(new java.awt.Color(153, 153, 153));
        lblBusinessClass.setText("Business Class");
        lblBusinessClass.setOpaque(true);
        lblBusinessClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBusinessClassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBusinessClassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBusinessClassMouseExited(evt);
            }
        });
        jPanel12.add(lblBusinessClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        lblExtra.setBackground(new java.awt.Color(51, 51, 51));
        lblExtra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblExtra.setForeground(new java.awt.Color(153, 153, 153));
        lblExtra.setText("Extra Class");
        lblExtra.setOpaque(true);
        lblExtra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExtraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExtraMouseEntered(evt);
            }
        });
        jPanel12.add(lblExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 90, 30));

        lblEconomic.setBackground(new java.awt.Color(51, 51, 51));
        lblEconomic.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEconomic.setForeground(new java.awt.Color(153, 153, 153));
        lblEconomic.setText("Economic Class");
        lblEconomic.setOpaque(true);
        lblEconomic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEconomicMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEconomicMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEconomicMouseExited(evt);
            }
        });
        jPanel12.add(lblEconomic, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 90, 30));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 350, -1));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 370, 608));

        jLabel9.setBackground(new java.awt.Color(204, 0, 51));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ADD NEW BOOKING");
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 950, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void lblBusinessClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBusinessClassMouseClicked
        Business b=new Business();
        pnlClassLoad.removeAll();
        pnlClassLoad.repaint();
        pnlClassLoad.revalidate();
        b.setSize(pnlClassLoad.getSize());
        pnlClassLoad.add(b);
        b.setVisible(true);
    }//GEN-LAST:event_lblBusinessClassMouseClicked

    private void lblExtraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExtraMouseClicked
        Extra ex=new Extra();
        pnlClassLoad.removeAll();
        pnlClassLoad.repaint();
        pnlClassLoad.revalidate();
        ex.setSize(pnlClassLoad.getSize());
        pnlClassLoad.add(ex);
        ex.setVisible(true);
    }//GEN-LAST:event_lblExtraMouseClicked

    private void lblEconomicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEconomicMouseClicked
        Econimic ec=new Econimic();
        pnlClassLoad.removeAll();
        pnlClassLoad.repaint();
        pnlClassLoad.revalidate();
        ec.setSize(pnlClassLoad.getSize());
        pnlClassLoad.add(ec);
        ec.setVisible(true);
    }//GEN-LAST:event_lblEconomicMouseClicked

    private void lblBusinessClassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBusinessClassMouseEntered
        lblBusinessClass.setBackground(Color.DARK_GRAY);
        lblBusinessClass.setForeground(Color.red);
    }//GEN-LAST:event_lblBusinessClassMouseEntered

    private void lblBusinessClassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBusinessClassMouseExited
        lblBusinessClass.setBackground(Color.BLACK);
        lblBusinessClass.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lblBusinessClassMouseExited

    private void lblEconomicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEconomicMouseEntered
        lblEconomic.setBackground(Color.DARK_GRAY);
        lblEconomic.setForeground(Color.red);
    }//GEN-LAST:event_lblEconomicMouseEntered

    private void lblEconomicMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEconomicMouseExited
        lblEconomic.setBackground(Color.BLACK);
        lblEconomic.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lblEconomicMouseExited

    private void lblExtraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExtraMouseEntered
        lblExtra.setBackground(Color.DARK_GRAY);
        lblExtra.setForeground(Color.red);
    }//GEN-LAST:event_lblExtraMouseEntered

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        AddNewPasenger adp=new AddNewPasenger();
        pnlpasengerLoad.removeAll();
        pnlpasengerLoad.repaint();
        pnlpasengerLoad.revalidate();
        adp.setSize(pnlpasengerLoad.getSize());
        pnlpasengerLoad.add(adp);
        adp.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void comboTripTYpeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTripTYpeActionPerformed
        if(comboTripTYpe.getSelectedItem().toString().equalsIgnoreCase("One Way")){
            returnDateChooser.setEnabled(false);
        }else{
            returnDateChooser.setEnabled(true);
        }
    }//GEN-LAST:event_comboTripTYpeActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
//        Details adp=new Details();
//        pnlDetails.removeAll();
//        pnlDetails.repaint();
//        pnlDetails.revalidate();
//        adp.setSize(pnlDetails.getSize());
//        pnlDetails.add(adp);
//        adp.setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tblLoadFlight.getModel(); 
        
        Date date = new Date();
      
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd", Locale.getDefault());
        String fromOrigin = cmbOrigin.getSelectedItem().toString();
        String toDestination = cmbDestination.getSelectedItem().toString();
        String originDate = sdf.format(departureDateChooser.getDate());
////        String returnDate = sdf.format(returnDateChooser.getDate());
        
        try {
             List<ShceduleDTO> allShcedule = ManageShceduleController.getAllShcedule();
           
            dtm.setRowCount(0);
             for (ShceduleDTO allShcedule1 : allShcedule) {

                 if (allShcedule1.getOrigin().equalsIgnoreCase(fromOrigin)){
                     if (allShcedule1.getDestination().equalsIgnoreCase(toDestination)) {
                         if (allShcedule1.getOriginTakeOffDate().equalsIgnoreCase(originDate)) {
                            Object[] rowData = {allShcedule1.getFlightDTO().getFlightName(),allShcedule1.getFlightDTO().getFlightNumber(),allShcedule1.getFlightDTO().getType(),allShcedule1.getOriginTakeOffTime(),allShcedule1.getDestinationTakeOffTime()};
                            dtm.addRow(rowData); 
                         }
                     }
                 }
                 }
             
           
        } catch (Exception ex) {
            Logger.getLogger(NewBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblLoadFlightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoadFlightMouseClicked
////
    }//GEN-LAST:event_tblLoadFlightMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbDestination;
    private javax.swing.JComboBox cmbOrigin;
    private javax.swing.JComboBox comboTripTYpe;
    private com.toedter.calendar.JDateChooser departureDateChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel165;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JLabel jLabel169;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel170;
    private javax.swing.JLabel jLabel171;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel188;
    private javax.swing.JLabel jLabel189;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private com.toedter.components.JSpinField jSpinField1;
    private com.toedter.components.JSpinField jSpinField2;
    private com.toedter.components.JSpinField jSpinField3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lblBusinessClass;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEconomic;
    private javax.swing.JLabel lblExtra;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel pnlClassLoad;
    private javax.swing.JPanel pnlDetails;
    private javax.swing.JPanel pnlpasengerLoad;
    private com.toedter.calendar.JDateChooser returnDateChooser;
    private javax.swing.JTable tblLoadFlight;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        java.util.Date d1 = new java.util.Date();
        SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-dd");
        String formateDate = df.format(d1);
        lblDate.setText(formateDate); 
    }

    private void setTime() {
       java.util.Date d1 = new java.util.Date();
       SimpleDateFormat df = new SimpleDateFormat("HH:mm:ss");
       String formateDate = df.format(d1);
       lblTime.setText(formateDate); 
    }

    private void loadcmbOrigin() {
          try {
            ArrayList<AirportDTO> all = (ArrayList<AirportDTO>) manageAirportController.getAllAirports();
            cmbOrigin.removeAll();
            for (AirportDTO all1 : all) {
                cmbOrigin.addItem(all1.getAirportName());

            }
        } catch (Exception ex) {
            Logger.getLogger(AddNewAirline.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadcmbDestination() {
        try {
            ArrayList<AirportDTO> all = (ArrayList<AirportDTO>) manageAirportController.getAllAirports();
            cmbDestination.removeAll();
            for (AirportDTO all1 : all) {
                cmbDestination.addItem(all1.getAirportName());

            }
        } catch (Exception ex) {
            Logger.getLogger(AddNewAirline.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
