/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.ars.viewserver;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
//import lk.ijse.ars.controller.ManageAirlineController;
import lk.ijse.ars.controller.ManageAirportController;
//import lk.ijse.ars.dto.AirlineDTO;
import lk.ijse.ars.dto.AirportDTO;
import lk.ijse.ars.observer.Observer;

/**
 *
 * @author USER
 */
public class AddNewAirline extends javax.swing.JPanel implements Observer{
    private ManageAirportController manageAirportController;
    //private boolean update = false;
    /**
     * Creates new form AddNewAirline
     */
    public AddNewAirline() {
        initComponents();
        loadAllAirports();
        loadAllAirlines();
        loadAllcmbCountry();
        try {
            UnicastRemoteObject.exportObject(this, 0);
            ManageAirportController.getSubject().registerObserver(this);
        } catch (RemoteException ex) {
            Logger.getLogger(AddNewAirline.class.getName()). log(Level.SEVERE,null,ex);
            
        }catch(Exception ex){
            Logger.getLogger(AddNewAirline.class.getName()). log(Level.SEVERE,null,ex);
        }
//        tblAirport.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
//
//            @Override
//            public void valueChanged(ListSelectionEvent e) {
//                if (tblAirport.getSelectedRow() == -1) {
//                    btnDelete.setEnabled(false);
//                    update = false;
//                    return;
//                }
//
//                try {
//
//                    if (reservedAirportID == "") {
//                        ManageAirportController.releaseAirport(reservedAirportID);
//                    }
//                    reservedAirportID = tblAirport.getValueAt(tblAirport.getSelectedRow(), 0).toString();
//                    boolean reserveAirport = ManageAirportController.reserveAirport(reservedAirportID);
//
//                    if (reserveAirport) {
//                        update = true;
//                        int row = tblAirport.getSelectedRow();
//
//                        txtAirportID.setText(tblAirport.getValueAt(row, 0).toString());
//                        txtAirportName.setText(tblAirport.getValueAt(row, 1).toString());
//                        txtCountry.setText(tblAirport.getValueAt(row, 2).toString());
//                        
//                    } else {
//                        update = false;
//                        JOptionPane.showMessageDialog(AddNewAirline.this, "Airport has been already reserved");
//                        tblAirport.clearSelection();
//                    }
//
//                } catch (Exception ex) {
//                    Logger.getLogger(AddNewAirline.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//            
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtAirlineID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAirlineName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAirline = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbCountry = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        txtAirportName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAirportID = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAirport = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblAddNewAirport = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 0, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADD NEW AIRLINE");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 1300, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Airline ID :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 54, 65, 26));

        txtAirlineID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirlineIDActionPerformed(evt);
            }
        });
        jPanel3.add(txtAirlineID, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 86, 270, -1));

        jLabel3.setText("Airline Name :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 112, 78, 26));

        txtAirlineName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirlineNameActionPerformed(evt);
            }
        });
        jPanel3.add(txtAirlineName, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 144, 270, -1));

        jLabel4.setText("Country :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 170, 65, 26));

        tblAirline.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline ID", "Airline Name", "Country"
            }
        ));
        tblAirline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAirlineMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAirline);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 253, 312, 108));

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Add");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 60, 30));

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Update");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 60, 30));

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Delete");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 60, 30));

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setOpaque(true);
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 389, 363, 50));

        jPanel3.add(cmbCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 270, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        txtAirportName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirportNameActionPerformed(evt);
            }
        });

        jLabel9.setText("Airport Name :");

        jLabel5.setText("Airport ID :");

        jLabel10.setText("Country :");

        txtAirportID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirportIDActionPerformed(evt);
            }
        });

        txtCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountryActionPerformed(evt);
            }
        });

        tblAirport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airport ID", "Airport Name", "Country"
            }
        ));
        tblAirport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAirportMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAirport);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAirportID, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAirportName, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 492, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAirportID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAirportName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 1300, 480));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Update");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        lblAddNewAirport.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAddNewAirport.setForeground(new java.awt.Color(204, 204, 204));
        lblAddNewAirport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddNewAirport.setText("Add");
        lblAddNewAirport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddNewAirportMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Delete");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(1096, Short.MAX_VALUE)
                .addComponent(lblAddNewAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAddNewAirport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 1380, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAirlineIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirlineIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirlineIDActionPerformed

    private void txtAirlineNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirlineNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirlineNameActionPerformed

    private void txtAirportIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirportIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirportIDActionPerformed

    private void txtAirportNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirportNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirportNameActionPerformed

    private void txtCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountryActionPerformed

    private void lblAddNewAirportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddNewAirportMouseClicked
       //AirportDTO airport = new AirportDTO(txtAirportID.getText(), txtAirportName.getText(), txtCountry.getText());
              try {
                  String airportId = txtAirportID.getText();
                  String airportName = txtAirportName.getText();
                  String country = txtCountry.getText();
                  
                  AirportDTO airportDTO = new AirportDTO(airportId, airportName, country);
//            boolean result = false;
//            
//            if (!update) {
//                result = ManageAirportController.addAirport(airport);
//            }else{
//                result = ManageAirportController.updateAirport(airport);
//            }
                  
              boolean isAdded = ManageAirportController.addAirport(airportDTO);
           
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Airport has been saved Successfully");
            }else{
                JOptionPane.showMessageDialog(this, "Failed to save the Airport");
            }
            loadAllAirports();
        } catch (Exception e) {
            Logger.getLogger(AddNewAirline.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_lblAddNewAirportMouseClicked

    private void tblAirportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAirportMouseClicked
        txtAirportID.setText(tblAirport.getValueAt(tblAirport.getSelectedRow(), 0).toString());
        txtAirportName.setText(tblAirport.getValueAt(tblAirport.getSelectedRow(), 1).toString());
        txtCountry.setText(tblAirport.getValueAt(tblAirport.getSelectedRow(), 2).toString());      
    }//GEN-LAST:event_tblAirportMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        try {
            ManageAirportController manageAirportController = new ManageAirportController();

            AirportDTO airportDTO = new AirportDTO();
            airportDTO.setAirportID(txtAirportID.getText());
            airportDTO.setAirportName(txtAirportName.getText());
            airportDTO.setCountry(txtCountry.getText());

            boolean isUpdate = ManageAirportController.updateAirport(airportDTO);
            if (isUpdate) {
                JOptionPane.showMessageDialog(this, "Update Success");
                loadAllAirports();
            } else {
                JOptionPane.showMessageDialog(this, "Update fail");
            }
        } catch (Exception ex) {
            Logger.getLogger(AddNewAirline.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
//        try {
//                  String airlineId = txtAirlineID.getText();
//                  String airlineName = txtAirlineName.getText();
//                  String country = cmbCountry.getSelectedItem().toString();
//                  
//                  AirlineDTO airlineDTO = new AirlineDTO(airlineId, airlineName, country);
////            boolean result = false;
////            
////            if (!update) {
////                result = ManageAirportController.addAirport(airport);
////            }else{
////                result = ManageAirportController.updateAirport(airport);
////            }
//                  
//              boolean isAdded = ManageAirlineController.addAirline(airlineDTO);
//           
//            if (isAdded) {
//                JOptionPane.showMessageDialog(this, "Airline has been saved Successfully");
//            }else{
//                JOptionPane.showMessageDialog(this, "Failed to save the Airline");
//            }
//            loadAllAirlines();
//        } catch (Exception e) {
//            Logger.getLogger(AddNewAirline.class.getName()).log(Level.SEVERE, null, e);
//        }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void tblAirlineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAirlineMouseClicked
        txtAirlineID.setText(tblAirline.getValueAt(tblAirline.getSelectedRow(), 0).toString());
        txtAirlineName.setText(tblAirline.getValueAt(tblAirline.getSelectedRow(), 1).toString());
        cmbCountry.setSelectedItem(tblAirline.getValueAt(tblAirline.getSelectedRow(), 2).toString());      
    }//GEN-LAST:event_tblAirlineMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbCountry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAddNewAirport;
    private javax.swing.JTable tblAirline;
    private javax.swing.JTable tblAirport;
    private javax.swing.JTextField txtAirlineID;
    private javax.swing.JTextField txtAirlineName;
    private javax.swing.JTextField txtAirportID;
    private javax.swing.JTextField txtAirportName;
    private javax.swing.JTextField txtCountry;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateObservers() throws Exception {
        loadAllAirports();
        loadAllAirlines();
    }

    private void loadAllAirports() {
        DefaultTableModel dtm = (DefaultTableModel) tblAirport.getModel();
        dtm.setRowCount(0);
        
        try {
            List<AirportDTO> airports = ManageAirportController.getAllAirports();
            
            if (airports == null) {
                return;
            }
            
            for (AirportDTO airport : airports) {
                Object[]rowData = {
                        airport.getAirportID(),
                        airport.getAirportName(),
                        airport.getCountry()
                        
                    };
                dtm.addRow(rowData);
            }
        } catch (Exception e) {
            Logger.getLogger(AddNewAirline.class.getName()).log(Level.SEVERE,null,e);
        }
    }

    private void loadAllcmbCountry() {
//        try {
//            ArrayList<AirportDTO> all = (ArrayList<AirportDTO>) manageAirportController.getAllAirports();
//            cmbCountry.removeAll();
//            for (AirportDTO all1 : all) {
//                cmbCountry.addItem(all1.getCountry());
//
//            }
//        } catch (Exception ex) {
//            Logger.getLogger(AddNewAirline.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    private void loadAllAirlines() {
//        DefaultTableModel dtm = (DefaultTableModel) tblAirline.getModel();
//        dtm.setRowCount(0);
//        
//        try {
//            List<AirlineDTO> airlines = ManageAirlineController.getAllAirline();
//            
//            if (airlines == null) {
//                return;
//            }
//            
//            for (AirlineDTO airline : airlines) {
//                Object[]rowData = {
//                        airline.getAirlineID(),
//                        airline.getAirlineName(),
//                        airline.getCountry()
//                        
//                    };
//                dtm.addRow(rowData);
//            }
//        } catch (Exception e) {
//            Logger.getLogger(AddNewAirline.class.getName()).log(Level.SEVERE,null,e);
//        }
    }
}
