/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.ars.viewserver;

import java.awt.Color;
import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;
//import lk.ijse.ars.controller.ManageAirlineController;
import lk.ijse.ars.controller.ManageAirportController;
import lk.ijse.ars.controller.ManageClassDetailsController;
import lk.ijse.ars.controller.ManageClassesController;
import lk.ijse.ars.controller.ManageFlightController;
import lk.ijse.ars.controller.ManageShceduleController;
//import lk.ijse.ars.dto.AirlineDTO;
import lk.ijse.ars.dto.AirportDTO;
import lk.ijse.ars.dto.ClassDetailsDTO;
import lk.ijse.ars.dto.ClassDetails_PKDTO;
import lk.ijse.ars.dto.ClassesDTO;
import lk.ijse.ars.dto.FlightDTO;
import lk.ijse.ars.dto.ShceduleDTO;
import lk.ijse.ars.observer.Observer;
import lk.ijse.ars.viewclient.Business;
import lk.ijse.ars.viewclient.Calander;
import lk.ijse.ars.viewclient.Econimic;
import lk.ijse.ars.viewclient.Extra;
import lk.ijse.ars.viewserver.Custom;

/**
 *
 * @author USER
 */
public class AddNewFlight_1 extends javax.swing.JPanel /*implements Observer*/ {

    private ManageAirportController manageAirportController;
//    private ManageAirlineController manageAirlineController;
    private ManageClassesController manageClassesController;
    private DefaultTableModel dtm;
//    String classes = "";

    /**
     * Creates new form AddNewFlight
     */
    public AddNewFlight_1() {
        initComponents();
        loadcmbAirline();
        loadcmbAirportOrigin();
        loadcmbAirportDestination();
        loadcmbClassName();
        loadcmbFlight();
        loadcmbFlightName();
        dtm = new DefaultTableModel();
//        try {
//            UnicastRemoteObject.exportObject(this, 0);
//            ManageFlightController.getSubject().registerObserver(this);
//        } catch (RemoteException ex) {
//            Logger.getLogger(AddNewAirline.class.getName()). log(Level.SEVERE,null,ex);
//            
//        }catch(Exception ex){
//            Logger.getLogger(AddNewAirline.class.getName()). log(Level.SEVERE,null,ex);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lblFliAdd1 = new javax.swing.JLabel();
        lblFliDelete1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        pnlLoadDefault = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtAirlineName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        txtFlightName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFlightID = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        pnlMapLoad = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtFlightNO = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        spinnerExWindow = new javax.swing.JSpinner();
        textClassFeeEx = new javax.swing.JTextField();
        spinnerExNormal = new javax.swing.JSpinner();
        cmbFlightName = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblClassDetails = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cmbClassName1 = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblShceduleDetails = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        cmbOrigin = new javax.swing.JComboBox();
        cmbDestination = new javax.swing.JComboBox();
        textTripCost = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        Date date = new Date();
        SpinnerDateModel sm = new SpinnerDateModel(date,null,null,Calendar.HOUR_OF_DAY);
        jSpinner1 = new javax.swing.JSpinner(sm);
        SpinnerDateModel sm1 = new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        jSpinner2 = new javax.swing.JSpinner(sm1);
        cmbFlight = new javax.swing.JComboBox();
        jPanel9 = new javax.swing.JPanel();
        lblFliAdd2 = new javax.swing.JLabel();
        lblFliDelete2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ars/icon/Material Icons_e22b(0)_32.png"))); // NOI18N
        jLabel16.setText("Update");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, 90, 30));

        lblFliAdd1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFliAdd1.setForeground(new java.awt.Color(255, 255, 255));
        lblFliAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ars/icon/octicons_f076(0)_48.png"))); // NOI18N
        lblFliAdd1.setText("Add");
        lblFliAdd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFliAdd1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFliAdd1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFliAdd1MouseExited(evt);
            }
        });
        jPanel2.add(lblFliAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, 80, 30));

        lblFliDelete1.setBackground(new java.awt.Color(255, 51, 51));
        lblFliDelete1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFliDelete1.setForeground(new java.awt.Color(255, 255, 255));
        lblFliDelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ars/icon/Entypo_e729(0)_32.png"))); // NOI18N
        lblFliDelete1.setText("Delete");
        lblFliDelete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFliDelete1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFliDelete1MouseExited(evt);
            }
        });
        jPanel2.add(lblFliDelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, 90, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLoadDefault.setOpaque(false);

        javax.swing.GroupLayout pnlLoadDefaultLayout = new javax.swing.GroupLayout(pnlLoadDefault);
        pnlLoadDefault.setLayout(pnlLoadDefaultLayout);
        pnlLoadDefaultLayout.setHorizontalGroup(
            pnlLoadDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        pnlLoadDefaultLayout.setVerticalGroup(
            pnlLoadDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jPanel6.add(pnlLoadDefault, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 130));

        jButton4.setBackground(new java.awt.Color(255, 0, 51));
        jButton4.setForeground(new java.awt.Color(255, 153, 153));
        jButton4.setText("Custom");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 102, -1));

        jLabel21.setBackground(new java.awt.Color(153, 153, 153));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Flight ID :");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 79, 24));
        jPanel6.add(txtAirlineName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 226, 25));

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setForeground(new java.awt.Color(0, 204, 255));
        jButton1.setText("Default");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 114, -1));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Class & Seat :");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 24));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Type :");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 72, 24));

        txtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeActionPerformed(evt);
            }
        });
        jPanel6.add(txtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 226, 25));
        jPanel6.add(txtFlightName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 226, 25));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Flight Name :");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 24));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Flight ID :");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 79, 24));
        jPanel6.add(txtFlightID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 226, 25));

        javax.swing.GroupLayout pnlMapLoadLayout = new javax.swing.GroupLayout(pnlMapLoad);
        pnlMapLoad.setLayout(pnlMapLoadLayout);
        pnlMapLoadLayout.setHorizontalGroup(
            pnlMapLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );
        pnlMapLoadLayout.setVerticalGroup(
            pnlMapLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Business");
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Business");
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(51, 51, 51));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Business");
        jLabel17.setOpaque(true);
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlMapLoad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMapLoad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 0, 280, 520));

        jLabel18.setBackground(new java.awt.Color(153, 153, 153));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Flight NO :");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 80, 24));

        txtFlightNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFlightNOActionPerformed(evt);
            }
        });
        jPanel6.add(txtFlightNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 226, 25));

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ars/icon/Select_White_(56).png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ars/icon/FontAwesome_f071(3)_36.png"))); // NOI18N
        jLabel13.setText(" Are You Sure ! ");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel13)
        );

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 390, 40));
        jPanel10.add(spinnerExWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 140, 27));

        textClassFeeEx.setForeground(new java.awt.Color(102, 102, 102));
        textClassFeeEx.setText("- Class Fee - ");
        textClassFeeEx.setToolTipText("");
        textClassFeeEx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textClassFeeExMouseClicked(evt);
            }
        });
        textClassFeeEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textClassFeeExActionPerformed(evt);
            }
        });
        jPanel10.add(textClassFeeEx, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 140, 30));
        jPanel10.add(spinnerExNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 140, 28));

        cmbFlightName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbFlightNameMouseClicked(evt);
            }
        });
        jPanel10.add(cmbFlightName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 140, 30));

        tblClassDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Class Name", "Flight Name", "Window SeatCount", "Normal Seat Count", "Class Fee"
            }
        ));
        jScrollPane3.setViewportView(tblClassDetails);

        jPanel10.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 220, 130));

        jLabel15.setText("Window Seat :");
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 140, -1));

        jLabel20.setText("Normal Seat :");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 140, -1));

        jPanel10.add(cmbClassName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, 30));

        jPanel6.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 266, 390, 260));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 700, 530));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblShceduleDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Origin", "Destination", "Origin Date", "Origin Time", "Destination Date", "Destination Time", "Trip Cost"
            }
        ));
        jScrollPane4.setViewportView(tblShceduleDetails);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 610, 110));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Destination Take Off Date :");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, 20));
        jPanel8.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 169, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Destination Take Off Time :");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Orgin Take Off Date :");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 147, 20));
        jPanel8.add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 169, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Orgin Take Off Time :");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 220, 20));

        cmbOrigin.setForeground(new java.awt.Color(153, 153, 153));
        cmbOrigin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Origin -" }));
        jPanel8.add(cmbOrigin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 430, 40));

        cmbDestination.setForeground(new java.awt.Color(153, 153, 153));
        cmbDestination.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Destination -" }));
        jPanel8.add(cmbDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 430, 40));

        textTripCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTripCostActionPerformed(evt);
            }
        });
        jPanel8.add(textTripCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 430, 40));
        jPanel8.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 580, 0));

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Trip Cost :");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 70, 36));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 10, 70));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 10, 70));

        JSpinner.DateEditor de = new JSpinner.DateEditor(jSpinner1, "hh:mm a");
        jSpinner1.setEditor(de);
        jPanel8.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 220, 40));

        JSpinner.DateEditor de1 = new JSpinner.DateEditor(jSpinner2, "hh:mm a");
        jSpinner2.setEditor(de1);
        jPanel8.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 220, 40));

        cmbFlight.setForeground(new java.awt.Color(153, 153, 153));
        cmbFlight.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Flight Name -" }));
        cmbFlight.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFlightItemStateChanged(evt);
            }
        });
        cmbFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFlightActionPerformed(evt);
            }
        });
        jPanel8.add(cmbFlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 430, 40));

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 600, 310));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));

        lblFliAdd2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFliAdd2.setForeground(new java.awt.Color(255, 255, 255));
        lblFliAdd2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ars/icon/octicons_f076(0)_48.png"))); // NOI18N
        lblFliAdd2.setText("Add");
        lblFliAdd2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFliAdd2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFliAdd2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFliAdd2MouseExited(evt);
            }
        });

        lblFliDelete2.setBackground(new java.awt.Color(255, 51, 51));
        lblFliDelete2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFliDelete2.setForeground(new java.awt.Color(255, 255, 255));
        lblFliDelete2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ars/icon/Entypo_e729(0)_32.png"))); // NOI18N
        lblFliDelete2.setText("Delete");
        lblFliDelete2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFliDelete2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFliDelete2MouseExited(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ars/icon/Material Icons_e22b(0)_32.png"))); // NOI18N
        jLabel19.setText("Update");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(320, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblFliAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblFliDelete2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFliAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFliDelete2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 610, 50));

        jLabel5.setBackground(new java.awt.Color(0, 0, 153));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ars/icon/FontAwesome_f072(1)_48.png"))); // NOI18N
        jLabel5.setText("ADD NEW FLIGHT");
        jLabel5.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Default c = new Default();
        pnlLoadDefault.removeAll();
        pnlLoadDefault.repaint();
        pnlLoadDefault.revalidate();
        c.setSize(pnlLoadDefault.getSize());
        pnlLoadDefault.add(c);
        c.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
//        Custom c = new Custom();
//        pnlCust.removeAll();
//        pnlCust.repaint();
//        pnlCust.revalidate();
//        c.setSize(pnlCust.getSize());
//        pnlCust.add(c);
//        c.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void textTripCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTripCostActionPerformed
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd", Locale.getDefault());
        SpinnerDateModel sm = new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);

        JSpinner.DateEditor de = new JSpinner.DateEditor(jSpinner1, "hh:mm a");
        String date1 = sdf.format(jDateChooser2.getDate());
        String date2 = sdf.format(jDateChooser3.getDate());

        String value1 = de.getFormat().format(jSpinner1.getValue());
        String value2 = de.getFormat().format(jSpinner2.getValue());

        dtm = (DefaultTableModel) tblShceduleDetails.getModel();
        Object[] rowData = {cmbOrigin.getSelectedItem(),cmbDestination.getSelectedItem(), date1, value1,  date2, value2, textTripCost.getText()};
        dtm.addRow(rowData);

    }//GEN-LAST:event_textTripCostActionPerformed

    private void lblFliAdd1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFliAdd1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFliAdd1MouseEntered

    private void lblFliAdd1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFliAdd1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFliAdd1MouseExited

    private void lblFliDelete1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFliDelete1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFliDelete1MouseEntered

    private void lblFliDelete1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFliDelete1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFliDelete1MouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        Business c = new Business();
        pnlMapLoad.removeAll();
        pnlMapLoad.repaint();
        pnlMapLoad.revalidate();
        c.setSize(pnlMapLoad.getSize());
        pnlMapLoad.add(c);
        c.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        Econimic c = new Econimic();
        pnlMapLoad.removeAll();
        pnlMapLoad.repaint();
        pnlMapLoad.revalidate();
        c.setSize(pnlMapLoad.getSize());
        pnlMapLoad.add(c);
        c.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        Extra c = new Extra();
        pnlMapLoad.removeAll();
        pnlMapLoad.repaint();
        pnlMapLoad.revalidate();
        c.setSize(pnlMapLoad.getSize());
        pnlMapLoad.add(c);
        c.setVisible(true);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void txtFlightNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFlightNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFlightNOActionPerformed

    private void lblFliAdd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFliAdd1MouseClicked
        try {
            String flightID = txtFlightID.getText();
            String flightName = txtFlightName.getText();
            String flightNO = txtFlightNO.getText();
            String type = txtType.getText();
            String airlineName = txtAirlineName.getText();
//            String airlineName = cmbAirline.getSelectedItem().toString();

            FlightDTO flightDTO = new FlightDTO();
            flightDTO.setFlightID(flightID);
            flightDTO.setFlightName(flightName);
            flightDTO.setFlightNumber(flightNO);
            flightDTO.setType(type);
            flightDTO.setAirlineID(airlineName);

//            AirlineDTO airlineDTO = new AirlineDTO();
//            airlineDTO.setAirlineID(airline);

//            flightDTO.setAirlineDTO(airlineDTO);
//            
            boolean isAdded = ManageFlightController.addFlight(flightDTO);

            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Shcedule has been saved Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Shcedule has been Faild");
            }
        } catch (Exception ex) {
            Logger.getLogger(AddNewFlight_1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblFliAdd1MouseClicked

    private void lblFliDelete2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFliDelete2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFliDelete2MouseEntered

    private void lblFliDelete2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFliDelete2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFliDelete2MouseExited

    private void lblFliAdd2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFliAdd2MouseClicked

//        Date date = new Date();
//        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd", Locale.getDefault());
//        SpinnerDateModel sm = new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
//
//        JSpinner.DateEditor de = new JSpinner.DateEditor(jSpinner1, "hh:mm a");
//        String date1 = sdf.format(jDateChooser2.getDate());
//        String date2 = sdf.format(jDateChooser3.getDate());
//
//        String value1 = de.getFormat().format(jSpinner1.getValue());
//        String value2 = de.getFormat().format(jSpinner2.getValue());
//        
//        ShceduleDTO shceduleDTO = new ShceduleDTO(, cmbOrigin.getSelectedItem(), cmbDestination.getSelectedItem(),date1, value1 date2, value2, textTripCost.getText(),new FlightDTO(txtFlightID,txtFlightName,txtFlightNO,txtType,null));
        try {
            FlightDTO findByName = ManageFlightController.findByName(cmbFlight.getSelectedItem().toString());
            System.out.println("CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" + findByName.getFlightName());
            if (findByName != null) {
                boolean addShcedule = false;
                ShceduleDTO shceduleDTO = null;
                DefaultTableModel dtmShcedule = (DefaultTableModel) tblShceduleDetails.getModel();
                for (int i = 0; i <= dtmShcedule.getRowCount(); i++) {
                    try {
//                        shceduleDTO.setShceduleID(0);
//                        shceduleDTO.setOrigin(dtmShcedule.getValueAt(i, 0).toString());
//                        shceduleDTO.setOriginTakeOffDate(dtmShcedule.getValueAt(i, 1).toString());
//                        shceduleDTO.setOriginTakeOffTime(dtmShcedule.getValueAt(i, 2).toString());
//                        shceduleDTO.setDestination(dtmShcedule.getValueAt(i, 3).toString());
//                        shceduleDTO.setDestinationTakeOffDate(dtmShcedule.getValueAt(i, 4).toString());
//                        shceduleDTO.setDestinationTakeOffTime(dtmShcedule.getValueAt(i, 5).toString());
//                        shceduleDTO.setTripCost(Double.parseDouble((String) dtmShcedule.getValueAt(i, 6)));
//                        shceduleDTO.setFlightDTO(findByName);
                        shceduleDTO = new ShceduleDTO(0,dtmShcedule.getValueAt(i, 0).toString(), dtmShcedule.getValueAt(i, 1).toString(), dtmShcedule.getValueAt(i, 2).toString(), (dtmShcedule.getValueAt(i, 3)).toString(), dtmShcedule.getValueAt(i, 4).toString(), (dtmShcedule.getValueAt(i, 5)).toString(), Double.parseDouble( dtmShcedule.getValueAt(i, 6).toString()), findByName);
                        addShcedule = ManageShceduleController.addShcedule(shceduleDTO, findByName);
                    } catch (Exception ex) {
                        Logger.getLogger(AddNewFlight_1.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

                shceduleDTO.setFlightDTO(findByName);//

                if (addShcedule) {
                    JOptionPane.showMessageDialog(this, "Shcedule has been saved Successfully");
                } else {
                    JOptionPane.showMessageDialog(this, "Shcedule has been Faild");
                }
            } else {
            }

        } catch (Exception ex) {
            Logger.getLogger(AddNewFlight_1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_lblFliAdd2MouseClicked

    private void lblFliAdd2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFliAdd2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFliAdd2MouseEntered

    private void lblFliAdd2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFliAdd2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFliAdd2MouseExited

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
///        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void cmbFlightItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFlightItemStateChanged

    }//GEN-LAST:event_cmbFlightItemStateChanged

    private void cmbFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFlightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFlightActionPerformed

    private void cmbFlightNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbFlightNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFlightNameMouseClicked

    private void textClassFeeExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textClassFeeExActionPerformed
        String wseatCount = spinnerExWindow.getValue().toString();
        String nseatCount = spinnerExNormal.getValue().toString();
        double classFee = Double.parseDouble(textClassFeeEx.getText());

        dtm = (DefaultTableModel) tblClassDetails.getModel();
        Object[] rowData = {cmbClassName1.getSelectedItem(),cmbFlightName.getSelectedItem(), wseatCount, nseatCount, classFee};
        dtm.addRow(rowData);
    }//GEN-LAST:event_textClassFeeExActionPerformed

    private void textClassFeeExMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textClassFeeExMouseClicked
        if (textClassFeeEx.getText().equalsIgnoreCase("- Class Fee - ")) {
            textClassFeeEx.setText("");
            textClassFeeEx.setForeground(Color.BLACK);
        }
        //        if (textClassFeeEcon.getText().equals("")) {
            //            textClassFeeEcon.setText("- Class Fee - ");
            //            textClassFeeEcon.setForeground(Color.GRAY);
            //        }
        //        if (textClassFeeBus.getText().equals("")) {
            //            textClassFeeBus.setText("- Class Fee - ");
            //            textClassFeeBus.setForeground(Color.GRAY);
            //        }
    }//GEN-LAST:event_textClassFeeExMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

        try {

            String flightID = cmbFlightName.getSelectedItem().toString();
            String classesID = cmbClassName1.getSelectedItem().toString();
            FlightDTO flightDTO = new FlightDTO();
            flightDTO.setFlightID(flightID);

            ClassesDTO classesDTO = new ClassesDTO();
            classesDTO.setClassID(classesID);

            //            FlightDTO flightDTO = ManageFlightController.findById(flightID);
            //                if (flightDTO.getFlightID().equals(flightDTO)) {
                //                    cmbFlightName.setSelectedItem(flightDTO.getFlightName());
                //
                //                ClassesDTO classesDTO = manageClassesController.findById(classesID);
                //                if (classesDTO.getClassID().equals(classesDTO)) {
                    //                    cmbClassName1.setSelectedItem(classesDTO.getClassName());
                    boolean addClassDetails = false;
                    DefaultTableModel dtmClassDetails = (DefaultTableModel) tblClassDetails.getModel();
                    for (int i = 0; i <= dtmClassDetails.getRowCount(); i++) {

                        try {
                            ClassDetailsDTO classDetailsDTO = new ClassDetailsDTO();
                            classDetailsDTO.setWindowSeatCount(dtmClassDetails.getValueAt((i), 4).toString());
                            classDetailsDTO.setNormalSeatCount(dtmClassDetails.getValueAt((i), 3).toString());
                            classDetailsDTO.setClassFee((Double.parseDouble( dtmClassDetails.getValueAt((i), 2).toString())));
                            classesDTO.setClassName(dtmClassDetails.getValueAt((i), 0).toString());
                            flightDTO.setFlightName(dtmClassDetails.getValueAt(i, 1).toString());
                            classesDTO.setClassID(classesID);
                            flightDTO.setFlightID(flightID);
                            new ClassDetails_PKDTO(classesID, flightID);

                            //                    classDetailsDTO = new ClassDetailsDTO(dtmClassDetails.getValueAt(i, 0).toString(), dtmClassDetails.getValueAt(i, 1).toString(), dtmClassDetails.getValueAt(i, 2).toString(), (dtmClassDetails.getValueAt(i, 3)).toString(), dtmClassDetails.getValueAt(i, 4).toString(), (dtmClassDetails.getValueAt(i, 5)).toString(), Double.parseDouble( dtmClassDetails.getValueAt(i, 3).toString()), findByName);

                            addClassDetails = ManageClassDetailsController.addClassDetails(classDetailsDTO, classesDTO, flightDTO);
                        } catch (Exception ex) {
                            Logger.getLogger(AddNewFlight_1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                    if (addClassDetails) {
                        JOptionPane.showMessageDialog(this, "ClassDetails has been saved Successfully");
                    } else {
                        JOptionPane.showMessageDialog(this, "ClassDetails has been Faild");
                    }

                } catch (Exception ex) {
                    Logger.getLogger(AddNewFlight_1.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_jLabel7MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbClassName1;
    private javax.swing.JComboBox cmbDestination;
    private javax.swing.JComboBox cmbFlight;
    private javax.swing.JComboBox cmbFlightName;
    private javax.swing.JComboBox cmbOrigin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JLabel lblFliAdd1;
    private javax.swing.JLabel lblFliAdd2;
    private javax.swing.JLabel lblFliDelete1;
    private javax.swing.JLabel lblFliDelete2;
    private javax.swing.JPanel pnlLoadDefault;
    private javax.swing.JPanel pnlMapLoad;
    private javax.swing.JSpinner spinnerExNormal;
    private javax.swing.JSpinner spinnerExWindow;
    private javax.swing.JTable tblClassDetails;
    private javax.swing.JTable tblShceduleDetails;
    private javax.swing.JTextField textClassFeeEx;
    private javax.swing.JTextField textTripCost;
    private javax.swing.JTextField txtAirlineName;
    private javax.swing.JTextField txtFlightID;
    private javax.swing.JTextField txtFlightNO;
    private javax.swing.JTextField txtFlightName;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables

    private FlightDTO ff;

    private void loadcmbAirportOrigin() {
        try {
            ArrayList<AirportDTO> all = (ArrayList<AirportDTO>) manageAirportController.getAllAirports();
            cmbOrigin.removeAll();
            for (AirportDTO all1 : all) {
                cmbOrigin.addItem(all1.getAirportName());

            }
        } catch (Exception ex) {
            Logger.getLogger(AddNewAirline.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadcmbAirportDestination() {
        try {
            ArrayList<AirportDTO> all = (ArrayList<AirportDTO>) manageAirportController.getAllAirports();
            cmbDestination.removeAll();
            for (AirportDTO all1 : all) {
                cmbDestination.addItem(all1.getAirportName());

            }
        } catch (Exception ex) {
            Logger.getLogger(AddNewAirline.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadcmbAirline() {
//        try {
//            ArrayList<AirlineDTO> all = (ArrayList<AirlineDTO>) manageAirlineController.getAllAirline();
//            cmbAirline.removeAll();
//            for (AirlineDTO all1 : all) {
//                cmbAirline.addItem(all1.getAirlineName());
//
//            }
//        } catch (Exception ex) {
//            Logger.getLogger(AddNewAirline.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

//    @Override
//    public void updateObservers() throws Exception {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
    private void loadcmbClassName() {
        try {
            ArrayList<ClassesDTO> all = (ArrayList<ClassesDTO>) manageClassesController.getAllClasses();
            cmbClassName1.removeAll();
            for (ClassesDTO all1 : all) {
                cmbClassName1.addItem(all1.getClassName());

            }
        } catch (Exception ex) {
            Logger.getLogger(AddNewFlight_1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadcmbFlightName() {

        try {
            ArrayList<FlightDTO> all = (ArrayList<FlightDTO>) ManageFlightController.getAllFlight();
            cmbFlightName.removeAll();
            for (FlightDTO all1 : all) {
                cmbFlightName.addItem(all1.getFlightName());
            }
        } catch (Exception e) {
            Logger.getLogger(AddNewFlight_1.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void loadcmbFlight() {
        try {
            ArrayList<FlightDTO> all = (ArrayList<FlightDTO>) ManageFlightController.getAllFlight();
            cmbFlight.removeAll();
            for (FlightDTO all1 : all) {
                cmbFlight.addItem(all1.getFlightName());
//                System.out.println("????????"+all1.getFlightName());
            }
        } catch (Exception ex) {
            Logger.getLogger(AddNewFlight_1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
