/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.ars.viewserver;

import java.awt.Color;
import java.text.SimpleDateFormat;
import lk.ijse.ars.viewclient.NewLogin;


/**
 *
 * @author USER
 */
public class AdminDash extends javax.swing.JFrame {

    /**
     * Creates new form AdminDash
     */
    public AdminDash() {
        initComponents();
        setDate();
        setTime();
        ServerHome sp = new ServerHome();
        pnlMain.removeAll();
        pnlMain.repaint();
        pnlMain.revalidate();
        sp.setSize(pnlMain.getSize());
        pnlMain.add(sp);
        sp.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblTimeMain = new javax.swing.JLabel();
        lblDateMain = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        lblAddNewFlight = new javax.swing.JLabel();
        lblCreatPayment = new javax.swing.JLabel();
        lblSearchPasenger1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Castellar", 0, 32)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Reservation System");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 400, 40));

        jLabel15.setFont(new java.awt.Font("Algerian", 0, 56)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 255));
        jLabel15.setText("AirGO");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 230, 60));

        lblTimeMain.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        lblTimeMain.setForeground(new java.awt.Color(255, 255, 255));
        lblTimeMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblTimeMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 70, 170, 50));

        lblDateMain.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        lblDateMain.setForeground(new java.awt.Color(255, 255, 255));
        lblDateMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblDateMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 50, 220, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ars/icon/Iconic_2718(0)_96.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 0, 80, 60));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ars/icon/octicons_f08d(0)_48.png"))); // NOI18N
        jLabel6.setText("HOME");
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add New AirLine");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 170, 40));

        lblLogout.setBackground(new java.awt.Color(0, 0, 0));
        lblLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(153, 153, 153));
        lblLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogout.setText("LogOut");
        lblLogout.setOpaque(true);
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });
        jPanel3.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 160, 40));

        lblAddNewFlight.setBackground(new java.awt.Color(0, 0, 0));
        lblAddNewFlight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddNewFlight.setForeground(new java.awt.Color(153, 153, 153));
        lblAddNewFlight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddNewFlight.setText("Add New Flight");
        lblAddNewFlight.setOpaque(true);
        lblAddNewFlight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddNewFlightMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAddNewFlightMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddNewFlightMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAddNewFlightMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblAddNewFlightMouseReleased(evt);
            }
        });
        jPanel3.add(lblAddNewFlight, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 160, 40));

        lblCreatPayment.setBackground(new java.awt.Color(0, 0, 0));
        lblCreatPayment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCreatPayment.setForeground(new java.awt.Color(153, 153, 153));
        lblCreatPayment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreatPayment.setText("Creat Payment");
        lblCreatPayment.setOpaque(true);
        lblCreatPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCreatPaymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCreatPaymentMouseExited(evt);
            }
        });
        jPanel3.add(lblCreatPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 160, 40));

        lblSearchPasenger1.setBackground(new java.awt.Color(0, 0, 0));
        lblSearchPasenger1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSearchPasenger1.setForeground(new java.awt.Color(153, 153, 153));
        lblSearchPasenger1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearchPasenger1.setText("Search Pasenger");
        lblSearchPasenger1.setOpaque(true);
        lblSearchPasenger1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSearchPasenger1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSearchPasenger1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSearchPasenger1MouseExited(evt);
            }
        });
        jPanel3.add(lblSearchPasenger1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 160, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ars/image/about.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 130));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ars/icon/Iconic_2718(0)_96.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 80, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 130));

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jPanel1.add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1370, 640));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        NewLogin nl = new NewLogin();
        nl.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblAddNewFlightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddNewFlightMouseClicked
        AddNewFlight_1 anf = new AddNewFlight_1();
        pnlMain.removeAll();
        pnlMain.repaint();
        pnlMain.revalidate();
        anf.setSize(pnlMain.getSize());
        pnlMain.add(anf);
        anf.setVisible(true);
    }//GEN-LAST:event_lblAddNewFlightMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void lblAddNewFlightMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddNewFlightMouseEntered
        lblAddNewFlight.setBackground(Color.GRAY);
        lblAddNewFlight.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblAddNewFlightMouseEntered

    private void lblAddNewFlightMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddNewFlightMouseExited
        lblAddNewFlight.setBackground(Color.BLACK);
        lblAddNewFlight.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lblAddNewFlightMouseExited

    private void lblCreatPaymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreatPaymentMouseEntered
        lblCreatPayment.setBackground(Color.GRAY);
        lblCreatPayment.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblCreatPaymentMouseEntered

    private void lblCreatPaymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreatPaymentMouseExited
       lblCreatPayment.setBackground(Color.BLACK);
       lblCreatPayment.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lblCreatPaymentMouseExited

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        lblLogout.setBackground(Color.GRAY);
        lblLogout.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        lblLogout.setBackground(Color.BLACK);
        lblLogout.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lblLogoutMouseExited

    private void lblAddNewFlightMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddNewFlightMousePressed
        
    }//GEN-LAST:event_lblAddNewFlightMousePressed

    private void lblAddNewFlightMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddNewFlightMouseReleased
        
    }//GEN-LAST:event_lblAddNewFlightMouseReleased

    private void lblSearchPasenger1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchPasenger1MouseClicked
        SerachPasenger sp = new SerachPasenger();
        pnlMain.removeAll();
        pnlMain.repaint();
        pnlMain.revalidate();
        sp.setSize(pnlMain.getSize());
        pnlMain.add(sp);
        sp.setVisible(true);
    }//GEN-LAST:event_lblSearchPasenger1MouseClicked

    private void lblSearchPasenger1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchPasenger1MouseEntered
        lblSearchPasenger1.setBackground(Color.GRAY);
        lblSearchPasenger1.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblSearchPasenger1MouseEntered

    private void lblSearchPasenger1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchPasenger1MouseExited
        lblSearchPasenger1.setBackground(Color.BLACK);
        lblSearchPasenger1.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lblSearchPasenger1MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        ServerHome sp = new ServerHome();
        pnlMain.removeAll();
        pnlMain.repaint();
        pnlMain.revalidate();
        sp.setSize(pnlMain.getSize());
        pnlMain.add(sp);
        sp.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        AddNewAirline sp = new AddNewAirline();
        pnlMain.removeAll();
        pnlMain.repaint();
        pnlMain.revalidate();
        sp.setSize(pnlMain.getSize());
        pnlMain.add(sp);
        sp.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setBackground(Color.GRAY);
        jLabel2.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
       jLabel2.setBackground(Color.BLACK);
       jLabel2.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jLabel2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAddNewFlight;
    private javax.swing.JLabel lblCreatPayment;
    private javax.swing.JLabel lblDateMain;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblSearchPasenger1;
    public static javax.swing.JLabel lblTimeMain;
    public static javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        java.util.Date d1 = new java.util.Date();
        SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-dd");
        String formateDate = df.format(d1);
        lblDateMain.setText(formateDate);
    }

    private void setTime() {
        java.util.Date d1 = new java.util.Date();
        SimpleDateFormat df = new SimpleDateFormat("HH:mm:ss");
        String formateDate = df.format(d1);
        lblTimeMain.setText(formateDate);
    }
}
